[package]
name = "turbo-hearts"
version = "0.1.0"
authors = ["Tim Wilson <twilson@palantir.com>"]
edition = "2018"

[dependencies]
env_logger = "*"
num_enum = "*"
rand = "*"
r2d2 = "*"
r2d2_sqlite = "*"
rusqlite = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
tokio = { version = "*", features = ["blocking", "macros", "rt-threaded", "sync"] }
uuid = { version = "*", features = ["serde", "v4"] }
warp = "*"
