import { EventData } from "./types";

export const FULL_GAME: EventData[] = [
  {
    type: "sit",
    north: { type: "human", name: "dan" },
    east: { type: "bot", name: "qrowland (bot)", algorithm: "random" },
    south: { type: "bot", name: "gmarquez (bot)", algorithm: "random" },
    west: { type: "bot", name: "crusso (bot)", algorithm: "random" },
    rules: "classic"
  },
  {
    type: "deal",
    north: ["JS", "5S", "AH", "JH", "TH", "8H", "7H", "3H", "6D", "2D", "TC", "6C", "3C"],
    east: ["TS", "7S", "4S", "KH", "6H", "5H", "4H", "5D", "QC", "JC", "8C", "7C", "5C"],
    south: ["AS", "6S", "2S", "QH", "AD", "QD", "JD", "TD", "8D", "4D", "KC", "9C", "4C"],
    west: ["KS", "QS", "9S", "8S", "3S", "9H", "2H", "KD", "9D", "7D", "3D", "AC", "2C"],
    pass: "left"
  },
  { type: "send_pass", from: "south", cards: ["AS", "6S", "2S"] },
  { type: "send_pass", from: "west", cards: ["KS", "9S", "3D"] },
  { type: "recv_pass", to: "west", cards: ["AS", "6S", "2S"] },
  { type: "send_pass", from: "east", cards: ["TS", "7S", "4S"] },
  { type: "recv_pass", to: "south", cards: ["TS", "7S", "4S"] },
  { type: "send_pass", from: "north", cards: ["6D", "2D", "TC"] },
  { type: "recv_pass", to: "north", cards: ["KS", "9S", "3D"] },
  { type: "recv_pass", to: "east", cards: ["6D", "2D", "TC"] },
  { type: "charge", seat: "east", cards: [] },
  { type: "charge", seat: "west", cards: [] },
  { type: "charge", seat: "south", cards: ["JD"] },
  { type: "charge", seat: "east", cards: [] },
  { type: "charge", seat: "west", cards: [] },
  { type: "charge", seat: "north", cards: ["AH"] },
  { type: "charge", seat: "east", cards: [] },
  { type: "charge", seat: "west", cards: [] },
  { type: "charge", seat: "south", cards: [] },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "2C" },
  { type: "play", seat: "north", card: "6C" },
  { type: "play", seat: "east", card: "JC" },
  { type: "play", seat: "south", card: "KC" },
  { type: "end_trick", winner: "south" },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "7S" },
  { type: "play", seat: "west", card: "3S" },
  { type: "play", seat: "north", card: "JS" },
  { type: "play", seat: "east", card: "5H" },
  { type: "end_trick", winner: "north" },
  { type: "start_trick", leader: "north" },
  { type: "play", seat: "north", card: "3D" },
  { type: "play", seat: "east", card: "5D" },
  { type: "play", seat: "south", card: "AD" },
  { type: "play", seat: "west", card: "KD" },
  { type: "end_trick", winner: "south" },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "4C" },
  { type: "play", seat: "west", card: "AC" },
  { type: "play", seat: "north", card: "3C" },
  { type: "play", seat: "east", card: "TC" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "2S" },
  { type: "play", seat: "north", card: "KS" },
  { type: "play", seat: "east", card: "QC" },
  { type: "play", seat: "south", card: "4S" },
  { type: "end_trick", winner: "north" },
  { type: "start_trick", leader: "north" },
  { type: "play", seat: "north", card: "9S" },
  { type: "play", seat: "east", card: "5C" },
  { type: "play", seat: "south", card: "TS" },
  { type: "play", seat: "west", card: "8S" },
  { type: "play", seat: "north", card: "5S" },
  { type: "play", seat: "east", card: "2D" },
  { type: "play", seat: "south", card: "QH" },
  { type: "play", seat: "west", card: "QS" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "7D" },
  { type: "play", seat: "north", card: "AH" },
  { type: "play", seat: "east", card: "6D" },
  { type: "play", seat: "south", card: "JD" },
  { type: "end_trick", winner: "south" },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "9C" },
  { type: "play", seat: "west", card: "6S" },
  { type: "play", seat: "north", card: "JH" },
  { type: "play", seat: "east", card: "7C" },
  { type: "play", seat: "south", card: "QD" },
  { type: "play", seat: "west", card: "9D" },
  { type: "play", seat: "north", card: "TH" },
  { type: "play", seat: "east", card: "8C" },
  { type: "end_trick", winner: "south" },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "8D" },
  { type: "play", seat: "west", card: "9H" },
  { type: "play", seat: "north", card: "8H" },
  { type: "play", seat: "east", card: "4H" },
  { type: "end_trick", winner: "south" },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "4D" },
  { type: "play", seat: "west", card: "2H" },
  { type: "play", seat: "north", card: "7H" },
  { type: "play", seat: "east", card: "6H" },
  { type: "end_trick", winner: "south" },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "TD" },
  { type: "play", seat: "west", card: "AS" },
  { type: "play", seat: "north", card: "3H" },
  { type: "play", seat: "east", card: "KH" },
  { type: "end_trick", winner: "south" }
];
