import { EventData } from "./types";

export const HIDDEN_GAME: EventData[] = [
  {
    type: "sit",
    north: { type: "bot", name: "qyork (bot)", algorithm: "random" },
    east: { type: "bot", name: "ypotts (bot)", algorithm: "random" },
    south: { type: "bot", name: "lpreston (bot)", algorithm: "random" },
    west: { type: "human", name: "dan" },
    rules: "classic"
  },
  {
    type: "deal",
    north: [],
    east: [],
    south: [],
    west: ["JS", "TS", "6S", "AH", "KH", "TH", "9H", "4H", "QD", "8D", "8C", "5C", "4C"],
    pass: "Left"
  },
  { type: "send_pass", from: "north", cards: [] },
  { type: "send_pass", from: "south", cards: [] },
  { type: "send_pass", from: "east", cards: [] },
  { type: "recv_pass", to: "east", cards: [] },
  { type: "recv_pass", to: "south", cards: [] },
  { type: "send_pass", from: "west", cards: ["TS", "QD", "8D"] },
  { type: "recv_pass", to: "west", cards: ["AS", "9S", "6C"] },
  { type: "recv_pass", to: "north", cards: [] },
  { type: "charge", seat: "east", cards: ["JD"] },
  { type: "charge", seat: "south", cards: [] },
  { type: "charge", seat: "north", cards: ["TC"] },
  { type: "charge", seat: "east", cards: [] },
  { type: "charge", seat: "south", cards: [] },
  { type: "charge", seat: "west", cards: [] },
  { type: "start_trick", leader: "south" },
  { type: "play", seat: "south", card: "2C" },
  { type: "play", seat: "west", card: "8C" },
  { type: "play", seat: "north", card: "AC" },
  { type: "play", seat: "east", card: "3C" },
  { type: "end_trick", winner: "north" },
  { type: "start_trick", leader: "north" },
  { type: "play", seat: "north", card: "TC" },
  { type: "play", seat: "east", card: "KC" },
  { type: "play", seat: "south", card: "7C" },
  { type: "play", seat: "west", card: "5C" },
  { type: "end_trick", winner: "east" },
  { type: "start_trick", leader: "east" },
  { type: "play", seat: "east", card: "TD" },
  { type: "play", seat: "south", card: "5D" },
  { type: "play", seat: "west", card: "6C" },
  { type: "play", seat: "north", card: "2D" },
  { type: "end_trick", winner: "east" },
  { type: "start_trick", leader: "east" },
  { type: "play", seat: "east", card: "5S" },
  { type: "play", seat: "south", card: "3S" },
  { type: "play", seat: "west", card: "9S" },
  { type: "play", seat: "north", card: "TS" },
  { type: "play", seat: "east", card: "2S" },
  { type: "play", seat: "south", card: "8S" },
  { type: "play", seat: "west", card: "6S" },
  { type: "play", seat: "north", card: "7H" },
  { type: "end_trick", winner: "north" },
  { type: "start_trick", leader: "north" },
  { type: "play", seat: "north", card: "3D" },
  { type: "play", seat: "east", card: "JD" },
  { type: "play", seat: "south", card: "6D" },
  { type: "play", seat: "west", card: "JS" },
  { type: "end_trick", winner: "east" },
  { type: "start_trick", leader: "east" },
  { type: "play", seat: "east", card: "5H" },
  { type: "play", seat: "south", card: "8H" },
  { type: "play", seat: "west", card: "9H" },
  { type: "play", seat: "north", card: "QH" },
  { type: "play", seat: "east", card: "6H" },
  { type: "play", seat: "south", card: "9C" },
  { type: "play", seat: "west", card: "KH" },
  { type: "play", seat: "north", card: "2H" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "AH" },
  { type: "play", seat: "north", card: "JH" },
  { type: "play", seat: "east", card: "3H" },
  { type: "play", seat: "south", card: "4D" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "TH" },
  { type: "play", seat: "north", card: "8D" },
  { type: "play", seat: "east", card: "QC" },
  { type: "play", seat: "south", card: "JC" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "4H" },
  { type: "play", seat: "north", card: "QD" },
  { type: "play", seat: "east", card: "KD" },
  { type: "play", seat: "south", card: "7S" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "AS" },
  { type: "play", seat: "north", card: "AD" },
  { type: "play", seat: "east", card: "QS" },
  { type: "play", seat: "south", card: "4S" },
  { type: "end_trick", winner: "west" },
  { type: "start_trick", leader: "west" },
  { type: "play", seat: "west", card: "4C" },
  { type: "play", seat: "north", card: "9D" },
  { type: "play", seat: "east", card: "7D" },
  { type: "play", seat: "south", card: "KS" },
  { type: "end_trick", winner: "west" }
];
