name: Push

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-cache-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-yarn-

      - name: Cache target
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cache-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-target-

      - name: Cache .cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cache-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-cargo-

      - name: Install pax
        run: cargo install pax

      - name: Yarn install
        run: yarn install
        working-directory: packages/game

      - name: Yarn build
        run: yarn build
        working-directory: packages/game

      - name: Install musl
        run: sudo apt-get install musl-tools

      - name: Add rust target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Cargo build
        run: cargo build --target x86_64-unknown-linux-musl --release --verbose

      - name: Cargo test
        run: cargo test --target x86_64-unknown-linux-musl --release --verbose

      - name: Make dist
        run: ./scripts/make-dist.sh

      - name: Deploy dist
        if: github.ref == 'ref/head/master'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: turbo-hearts.tgz
          target: /opt
          overwrite: true

      - name: Run dist
        if: github.ref == 'ref/head/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: /opt/deploy-play.anti.run.sh

      - name: Upload dist
        uses: actions/upload-artifact@v1
        with:
          name: turbo-hearts.tgz
          path: turbo-hearts.tgz
