name: Push

on:
  push:
    branches:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: packages/game
      - name: Build Frontend
        run: yarn build:dev
        working-directory: packages/game
      - name: Build Backend
        run: cargo build --verbose
      - name: Test Backend
        run: cargo test --verbose
