name: Push

on:
  push:
    branches:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-cache-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Cache target
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cache-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-target-

      - name: Cache .cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cache-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-cargo-

      - name: Yarn install
        run: yarn install
        working-directory: packages/game

      - name: Yarn build
        run: yarn build
        working-directory: packages/game

      - name: Cargo build
        run: cargo build --verbose

      - name: Cargo test
        run: cargo test --verbose
