name: Push

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: echo ${{github.ref}}
      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: packages/game
      - name: Build Frontend
        run: yarn build:prod
        working-directory: packages/game
      - name: Build Backend
        run: cargo build --release --verbose
      - name: Test Backend
        run: cargo test --release --verbose
      - name: Build Dist
        run: ./scripts/make-dist.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Dist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./turbo-hearts.tgz
          asset_name: turbo-hearts.tgz
          asset_content_type: application/gzip
