name: Release

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Yarn install
        run: yarn install
        working-directory: packages/game

      - name: Yarn Build
        run: yarn build:prod
        working-directory: packages/game

      - name: Install musl
        run: sudo apt-get install musl-tools

      - name: Add rust target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Cargo build
        run: cargo build --target x86_64-unknown-linux-musl --release --verbose

      - name: Make dist
        run: ./scripts/make-dist.sh

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./turbo-hearts.tgz
          asset_name: turbo-hearts.tgz
          asset_content_type: application/gzip
