name: Release

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: packages/game
      - name: Build Frontend
        run: yarn build:prod
        working-directory: packages/game
      - name: Install musl
        run: sudo apt-get install musl-tools
      - name: Install Rust Target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build Backend
        run: cargo build --target x86_64-unknown-linux-musl --release --verbose
      - name: Build Dist
        run: ./scripts/make-dist.sh
      - name: Upload Dist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./turbo-hearts.tgz
          asset_name: turbo-hearts.tgz
          asset_content_type: application/gzip
