name: Release

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Pax
        run: cargo install pax

      - name: Yarn install (game)
        run: yarn install
        working-directory: packages/game

      - name: Yarn build (game)
        run: yarn build
        working-directory: packages/game

      - name: Yarn install (lobby)
        run: yarn install
        working-directory: packages/lobby

      - name: Yarn build (lobby)
        run: yarn build
        working-directory: packages/lobby

      - name: Install musl
        run: sudo apt-get install musl-tools

      - name: Add rust target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Cargo build
        run: cargo build --target x86_64-unknown-linux-musl --release --verbose

      - name: Make dist
        run: ./scripts/make-dist.sh

      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./turbo-hearts.tgz
          asset_name: turbo-hearts.tgz
          asset_content_type: application/gzip
